const CUISINES = [
  "Danish",
  "Egyptian",
  "Polish",
  "American",
  "Kurdish",
  "Brazilian",
  "Somali",
  "Portuguese",
  "Spanish",
  "Fish & Chips",
  "Maharashtrian",
  "Ainu",
  "German",
  "Thai",
  "British",
  "Tex-Mex",
  "Cambodian",
  "Mughal",
  "Goan",
  "Creole",
  "Mexican",
  "Steak",
  "Eritrean",
  "South Indian",
  "Filipino",
  "Berber",
  "Serbian",
  "Modern English",
  "French",
  "Argentine",
  "Bashkir",
  "Arab",
  "Korean",
  "Buddhist",
  "Ukrainian",
  "Persian",
  "Irish",
  "Greek",
  "Circassian",
  "Chicken Shop",
  "Peruvian",
  "Israeli",
  "Latvian",
  "Chinese",
  "Indonesian",
  "Burgers",
  "Vietnamese",
  "Cypriot",
  "Chechen",
  "Lebanese",
  "Finnish",
  "Jamaican",
  "Azerbaijani",
  "Mangalorean",
  "Taiwanese",
  "Andhra",
  "Keralite",
  "Pakistani",
  "Cantonese",
  "Québécois",
  "Italian",
  "Bulgarian",
  "Uyghur",
  "Caribbean",
  "Turkish",
  "Cajun",
  "Lithuanian",
  "Punjabi",
  "Czech",
  "Russian",
  "Assyrian",
  "Japanese",
  "Balochi",
  "Armenian",
  "Sri Lankan",
  "Kazakh",
  "Albanian",
  "Ethiopian",
  "Romanian",
  "Bengali",
  "Georgian",
  "Laotian",
  "Nepalese",
  "Slovak",
  "Chukchi",
  "Indian",
  "Estonian",
  "Crimean Tatar",
  "Malay",
  "Hyderabad",
  "Italian-American",
];

export const getDinner = (pickAgain) => {
  if (pickAgain) {
    // they hated it 8{
    const newIndex = Math.floor(Math.random() * CUISINES.length);
    const newDinner = CUISINES[newIndex];
    CUISINES.splice(newIndex, 1); // remove this option so it doesnt repeat
    return newDinner;
  }
  const today = new Date();
  const day = today.getUTCMonth() + today.getUTCDate();
  let dateIndex = day;
  if (day > CUISINES.length) {
    dateIndex = -1 * (CUISINES.length - day);
  }
  return CUISINES[dateIndex - 1];
};
